// =====================================================================
// DATA.JS — All vocabulary, fidel chart, and conjugation data
// =====================================================================

const backgrounds = [
  "https://cdn.britannica.com/23/93423-004-EA6EF02B.jpg",
  "https://nextisafrica.com/sites/default/files/styles/galerie/public/2025-09/AFRIQUEMAGAZINE_466_20250708%20%283%29.pdf-image-020.jpg?h=1fc136cd&itok=mzis_7Xe",
  "https://momaa.org/wp-content/uploads/2019/10/15941556007_443e1d0fe9_b.png",
  "https://content.palacemuseum.gov.et/uploads/486614647_122120640440751386_6905596083102292556_n_7e8b38fba2.webp"
];

// ── 171 vocabulary items ──────────────────────────────────────────
const rawData = [
  {id:1,  pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ሰላም",         trans:"selam",                    eng:"Hello"},
  {id:2,  pos:"Noun",       cat:"Numbers",             amh:"ዜሮ",           trans:"zero",                     eng:"Zero"},
  {id:3,  pos:"Noun",       cat:"Numbers",             amh:"አንድ",          trans:"and",                      eng:"One"},
  {id:4,  pos:"Noun",       cat:"Numbers",             amh:"ሁለት",          trans:"hulet",                    eng:"Two"},
  {id:5,  pos:"Noun",       cat:"Numbers",             amh:"ሶስት",          trans:"sost",                     eng:"Three"},
  {id:6,  pos:"Noun",       cat:"Numbers",             amh:"አራት",          trans:"arat",                     eng:"Four"},
  {id:7,  pos:"Noun",       cat:"Numbers",             amh:"አምስት",         trans:"amist",                    eng:"Five"},
  {id:8,  pos:"Noun",       cat:"Numbers",             amh:"ስድስት",         trans:"sidist",                   eng:"Six"},
  {id:9,  pos:"Noun",       cat:"Numbers",             amh:"ሰባት",          trans:"sebat",                    eng:"Seven"},
  {id:10, pos:"Noun",       cat:"Numbers",             amh:"ስምንት",         trans:"simint",                   eng:"Eight"},
  {id:11, pos:"Noun",       cat:"Numbers",             amh:"ዘጠኝ",          trans:"zeTeñ",                    eng:"Nine"},
  {id:12, pos:"Noun",       cat:"Numbers",             amh:"አስር",          trans:"asir",                     eng:"Ten"},
  {id:13, pos:"Noun",       cat:"Numbers",             amh:"አስራ አንድ",      trans:"asra and",                 eng:"Eleven"},
  {id:14, pos:"Noun",       cat:"Numbers",             amh:"አስራ ሁለት",      trans:"asra hulet",               eng:"Twelve"},
  {id:15, pos:"Noun",       cat:"Numbers",             amh:"ሃያ",           trans:"haya",                     eng:"Twenty"},
  {id:16, pos:"Noun",       cat:"Numbers",             amh:"ሰላሳ",          trans:"selasa",                   eng:"Thirty"},
  {id:17, pos:"Noun",       cat:"Numbers",             amh:"አርባ",          trans:"arba",                     eng:"Forty"},
  {id:18, pos:"Noun",       cat:"Numbers",             amh:"አምሳ",          trans:"amsa",                     eng:"Fifty"},
  {id:19, pos:"Noun",       cat:"Numbers",             amh:"ስድሳ",          trans:"sidsa",                    eng:"Sixty"},
  {id:20, pos:"Noun",       cat:"Numbers",             amh:"ሰባ",           trans:"seba",                     eng:"Seventy"},
  {id:21, pos:"Noun",       cat:"Numbers",             amh:"ሰማንያ",         trans:"semanya",                  eng:"Eighty"},
  {id:22, pos:"Noun",       cat:"Numbers",             amh:"ዘጠና",          trans:"zeTena",                   eng:"Ninety"},
  {id:23, pos:"Noun",       cat:"Numbers",             amh:"መቶ",           trans:"meto",                     eng:"One Hundred"},
  {id:24, pos:"Noun",       cat:"Numbers",             amh:"ሁለት መቶ",       trans:"hulet meto",               eng:"Two Hundred"},
  {id:25, pos:"Noun",       cat:"Numbers",             amh:"ሺህ",           trans:"shih",                     eng:"One Thousand"},
  {id:26, pos:"Noun",       cat:"Numbers",             amh:"ሁለት ሽህ",       trans:"hulet shih",               eng:"Two Thousand"},
  {id:27, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"እንዴት ነህ?",   trans:"indet neh",                eng:"How are you? (m)"},
  {id:28, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"እንዴት ነሽ?",   trans:"indet nesh",               eng:"How are you? (f)"},
  {id:29, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"እንዴት ነዎት?",  trans:"indet nawot",              eng:"How are you? (formal)"},
  {id:30, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"እንዴት ናችሁ?",  trans:"indet nachu",              eng:"How are you? (plural)"},
  {id:31, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና እግዚአብሔር ይመስገን",trans:"dehna igziabher yimesgen",eng:"Good, thank God"},
  {id:32, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና አደርክ",   trans:"dehna aderk",              eng:"Good morning (m)"},
  {id:33, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና አደርሽ",   trans:"dehna adersh",             eng:"Good morning (f)"},
  {id:34, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና አደሩ",    trans:"dehna aderu",              eng:"Good morning (formal)"},
  {id:35, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና አደሪችሁ",  trans:"dehna aderachu",           eng:"Good morning (plural)"},
  {id:36, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደኅና ዋልክ",    trans:"dehna walk",               eng:"Good afternoon (m)"},
  {id:37, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ዋልሽ",    trans:"dehna walsh",              eng:"Good afternoon (f)"},
  {id:38, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ዋሉ",     trans:"dehna walu",               eng:"Good afternoon (formal)"},
  {id:39, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ዋላችሁ",   trans:"dehna walachu",            eng:"Good afternoon (plural)"},
  {id:40, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና እደር",    trans:"dehna ider",               eng:"Good night (m)"},
  {id:41, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና እደሪ",    trans:"dehna ideri",              eng:"Good night (f)"},
  {id:42, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና እደሩ",    trans:"dehna ideru",              eng:"Good night (formal/plural)"},
  {id:44, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ሁን",     trans:"dehna hun",                eng:"Good bye (m)"},
  {id:45, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ሁኝ",     trans:"dehna huñ",                eng:"Good bye (f)"},
  {id:46, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ደህና ሁኑ",     trans:"dehna hunu",               eng:"Good bye (formal/plural)"},
  {id:48, pos:"Interjection",cat:"Greetings & Goodbyes",amh:"ቻው",          trans:"chow",                     eng:"Good bye (casual)"},
  {id:49, pos:"Adjective",  cat:"Color",               amh:"ቀይ",          trans:"qey",                      eng:"Red"},
  {id:50, pos:"Adjective",  cat:"Color",               amh:"ብርቱካናማ",      trans:"birtukanama",              eng:"Orange"},
  {id:51, pos:"Adjective",  cat:"Color",               amh:"ቢጫ",          trans:"bicha",                    eng:"Yellow"},
  {id:52, pos:"Adjective",  cat:"Color",               amh:"አረንጓዴ",       trans:"arengwade",                eng:"Green"},
  {id:53, pos:"Adjective",  cat:"Color",               amh:"ሰማያዊ",        trans:"semayawi",                 eng:"Blue"},
  {id:54, pos:"Adjective",  cat:"Color",               amh:"ሐምራዊ",        trans:"hamrawi",                  eng:"Purple"},
  {id:55, pos:"Adjective",  cat:"Color",               amh:"ጥቁር",         trans:"Tiqur",                    eng:"Black"},
  {id:56, pos:"Adjective",  cat:"Color",               amh:"ነጭ",          trans:"nech",                     eng:"White"},
  {id:57, pos:"Adjective",  cat:"Color",               amh:"ቡኒ",          trans:"buni",                     eng:"Brown"},
  {id:58, pos:"Adjective",  cat:"Color",               amh:"ግራጫ",         trans:"gracha",                   eng:"Gray"},
  {id:59, pos:"Noun",       cat:"Family",              amh:"ወንድ",         trans:"wend",                     eng:"Man"},
  {id:60, pos:"Noun",       cat:"Family",              amh:"ሴት",          trans:"set",                      eng:"Woman"},
  {id:61, pos:"Noun",       cat:"Family",              amh:"ቤተሰብ",        trans:"beteseb",                  eng:"Family"},
  {id:62, pos:"Noun",       cat:"Family",              amh:"ልጅ",          trans:"lij",                      eng:"Child"},
  {id:63, pos:"Noun",       cat:"Family",              amh:"ልጆች",         trans:"lijoch",                   eng:"Children"},
  {id:64, pos:"Noun",       cat:"Family",              amh:"ሕጻን",         trans:"hitsan",                   eng:"Baby"},
  {id:65, pos:"Noun",       cat:"Family",              amh:"ወንድ ልጅ",      trans:"wend lij",                 eng:"Son"},
  {id:66, pos:"Noun",       cat:"Family",              amh:"ሴት ልጅ",       trans:"set lij",                  eng:"Daughter"},
  {id:67, pos:"Noun",       cat:"Family",              amh:"እናት",         trans:"enat",                     eng:"Mother"},
  {id:68, pos:"Noun",       cat:"Family",              amh:"አባት",         trans:"abat",                     eng:"Father"},
  {id:69, pos:"Noun",       cat:"Family",              amh:"የአጎት ልጅ",     trans:"ye'agot lij",              eng:"Cousin"},
  {id:70, pos:"Noun",       cat:"Family",              amh:"አክስት",        trans:"akist",                    eng:"Aunt"},
  {id:71, pos:"Noun",       cat:"Family",              amh:"አጎት",         trans:"agot",                     eng:"Uncle"},
  {id:72, pos:"Noun",       cat:"Family",              amh:"የወንድም ልጅ",    trans:"yewendim lij",             eng:"Nephew"},
  {id:73, pos:"Noun",       cat:"Family",              amh:"የእህት ልጅ",     trans:"ye'ihit lij",              eng:"Niece"},
  {id:74, pos:"Noun",       cat:"Family",              amh:"አያት",         trans:"ayat",                     eng:"Grandfather"},
  {id:75, pos:"Noun",       cat:"Family",              amh:"ሴት አያት",      trans:"set ayat",                 eng:"Grandmother"},
  {id:76, pos:"Noun",       cat:"Family",              amh:"ባል",          trans:"bal",                      eng:"Husband"},
  {id:77, pos:"Noun",       cat:"Family",              amh:"ሚስት",         trans:"mist",                     eng:"Wife"},
  {id:78, pos:"Pronoun",    cat:"Pronoun",             amh:"እኔ",          trans:"ine",                      eng:"I"},
  {id:79, pos:"Pronoun",    cat:"Pronoun",             amh:"አንተ",         trans:"ante",                     eng:"You (m)"},
  {id:80, pos:"Pronoun",    cat:"Pronoun",             amh:"አንቺ",         trans:"anchi",                    eng:"You (f)"},
  {id:81, pos:"Pronoun",    cat:"Pronoun",             amh:"እርስዎ",        trans:"irswo",                    eng:"You (formal/elder)"},
  {id:82, pos:"Pronoun",    cat:"Pronoun",             amh:"እናንተ",        trans:"inante",                   eng:"You (plural)"},
  {id:83, pos:"Pronoun",    cat:"Pronoun",             amh:"እሱ",          trans:"issu",                     eng:"He"},
  {id:84, pos:"Pronoun",    cat:"Pronoun",             amh:"እሷ",          trans:"issua",                    eng:"She"},
  {id:85, pos:"Pronoun",    cat:"Pronoun",             amh:"እሳቸው",        trans:"issachew",                 eng:"He/She (elder)"},
  {id:86, pos:"Pronoun",    cat:"Pronoun",             amh:"እኛ",          trans:"iña",                      eng:"We"},
  {id:87, pos:"Pronoun",    cat:"Pronoun",             amh:"እነሱ",         trans:"innessu",                  eng:"They"},
  {id:88, pos:"Verb",       cat:"Irregular",           amh:"መሄድ",         trans:"mehaed",                   eng:"to go"},
  {id:89, pos:"Verb",       cat:"Regular",             amh:"መላክ",         trans:"melak",                    eng:"to send"},
  {id:90, pos:"Verb",       cat:"Irregular",           amh:"መምጣት",        trans:"memTat",                   eng:"to come"},
  {id:91, pos:"Verb",       cat:"Regular",             amh:"መሞት",         trans:"memot",                    eng:"to die"},
  {id:92, pos:"Verb",       cat:"Regular",             amh:"መታየት",        trans:"metayet",                  eng:"to appear"},
  {id:93, pos:"Verb",       cat:"Regular",             amh:"መኖር",         trans:"menor",                    eng:"to live"},
  {id:94, pos:"Verb",       cat:"Regular",             amh:"መድረስ",        trans:"medires",                  eng:"to reach"},
  {id:95, pos:"Verb",       cat:"Regular",             amh:"መጠየቅ",        trans:"meTeyeq",                  eng:"to ask"},
  {id:96, pos:"Verb",       cat:"Regular",             amh:"መጨመር",        trans:"meCHemer",                 eng:"to add"},
  {id:97, pos:"Verb",       cat:"Irregular",           amh:"ማለት",         trans:"malet",                    eng:"to mean / to say"},
  {id:98, pos:"Verb",       cat:"Regular",             amh:"ማግኘት",        trans:"magñet",                   eng:"to find"},
  {id:100,pos:"Verb",       cat:"Irregular",           amh:"መሆን",         trans:"mehon",                    eng:"to be"},
  {id:101,pos:"Verb",       cat:"Regular",             amh:"መልቀቅ",        trans:"melqeq",                   eng:"to leave"},
  {id:102,pos:"Verb",       cat:"Regular",             amh:"መመልከት",       trans:"memelket",                 eng:"to look"},
  {id:103,pos:"Verb",       cat:"Regular",             amh:"መማር",         trans:"memar",                    eng:"to learn"},
  {id:104,pos:"Verb",       cat:"Regular",             amh:"መምራት",        trans:"memrat",                   eng:"to lead"},
  {id:105,pos:"Verb",       cat:"Regular",             amh:"መሞከር",        trans:"memoker",                  eng:"to try"},
  {id:106,pos:"Verb",       cat:"Regular",             amh:"መረዳት",        trans:"meredat",                  eng:"to understand"},
  {id:107,pos:"Verb",       cat:"Regular",             amh:"መራመድ",        trans:"meramed",                  eng:"to walk"},
  {id:108,pos:"Verb",       cat:"Regular",             amh:"መርዳት",        trans:"merdat",                   eng:"to help"},
  {id:109,pos:"Verb",       cat:"Regular",             amh:"መሮጥ",         trans:"meroT",                    eng:"to run"},
  {id:110,pos:"Verb",       cat:"Regular",             amh:"መሳብ",         trans:"mesab",                    eng:"to pull"},
  {id:111,pos:"Verb",       cat:"Regular",             amh:"መስማት",        trans:"mesmat",                   eng:"to hear"},
  {id:112,pos:"Verb",       cat:"Regular",             amh:"መስራት",        trans:"mesrat",                   eng:"to work"},
  {id:113,pos:"Verb",       cat:"Regular",             amh:"መስጠት",        trans:"mesTet",                   eng:"to give"},
  {id:114,pos:"Verb",       cat:"Regular",             amh:"መሸጥ",         trans:"mesheT",                   eng:"to sell"},
  {id:115,pos:"Verb",       cat:"Regular",             amh:"መቀመጥ",        trans:"meqemeT",                  eng:"to sit"},
  {id:116,pos:"Verb",       cat:"Regular",             amh:"መቀየር",        trans:"meqeyer",                  eng:"to change"},
  {id:117,pos:"Verb",       cat:"Regular",             amh:"መቀጠል",        trans:"meqeTel",                  eng:"to continue"},
  {id:118,pos:"Verb",       cat:"Regular",             amh:"መቆም",         trans:"meqom",                    eng:"to stand"},
  {id:119,pos:"Verb",       cat:"Regular",             amh:"መቆየት",        trans:"meqoyet",                  eng:"to wait"},
  {id:120,pos:"Verb",       cat:"Regular",             amh:"መናገር",        trans:"menager",                  eng:"to speak"},
  {id:121,pos:"Verb",       cat:"Regular",             amh:"መንቀሳቀስ",      trans:"menqesaqes",               eng:"to move"},
  {id:122,pos:"Verb",       cat:"Regular",             amh:"መንገር",        trans:"menger",                   eng:"to tell"},
  {id:123,pos:"Verb",       cat:"Regular",             amh:"መከተል",        trans:"meketel",                  eng:"to follow"},
  {id:124,pos:"Verb",       cat:"Regular",             amh:"መክፈል",        trans:"mekfel",                   eng:"to pay"},
  {id:125,pos:"Verb",       cat:"Regular",             amh:"መክፈት",        trans:"mekfet",                   eng:"to open"},
  {id:126,pos:"Verb",       cat:"Regular",             amh:"መወሰን",        trans:"mewesen",                  eng:"to decide"},
  {id:127,pos:"Verb",       cat:"Regular",             amh:"መውሰድ",        trans:"mewsed",                   eng:"to take"},
  {id:128,pos:"Verb",       cat:"Regular",             amh:"መውደቅ",        trans:"mewdeq",                   eng:"to fall"},
  {id:129,pos:"Verb",       cat:"Regular",             amh:"መውደድ",        trans:"mewded",                   eng:"to like"},
  {id:130,pos:"Verb",       cat:"Regular",             amh:"መያዝ",         trans:"meyaz",                    eng:"to hold"},
  {id:131,pos:"Verb",       cat:"Regular",             amh:"መጀመር",        trans:"mejemer",                  eng:"to begin"},
  {id:132,pos:"Verb",       cat:"Regular",             amh:"መገንባት",       trans:"megenbat",                 eng:"to build"},
  {id:133,pos:"Verb",       cat:"Regular",             amh:"መግዛት",        trans:"megzat",                   eng:"to buy"},
  {id:134,pos:"Verb",       cat:"Regular",             amh:"መጠቀም",        trans:"meTeqem",                  eng:"to use"},
  {id:135,pos:"Verb",       cat:"Regular",             amh:"መጠበቅ",        trans:"meTebeq",                  eng:"to keep"},
  {id:136,pos:"Verb",       cat:"Regular",             amh:"መጥራት",        trans:"meTrat",                   eng:"to call"},
  {id:137,pos:"Verb",       cat:"Regular",             amh:"መጫወት",        trans:"meCHawet",                 eng:"to play"},
  {id:138,pos:"Verb",       cat:"Regular",             amh:"መፃፍ",         trans:"metsaf",                   eng:"to write"},
  {id:139,pos:"Verb",       cat:"Regular",             amh:"መፈለግ",        trans:"mefeleg",                  eng:"to want"},
  {id:140,pos:"Verb",       cat:"Regular",             amh:"መፍቀድ",        trans:"mefqed",                   eng:"to let / to allow"},
  {id:141,pos:"Verb",       cat:"Regular",             amh:"ማለፍ",         trans:"malef",                    eng:"to pass"},
  {id:142,pos:"Verb",       cat:"Regular",             amh:"ማመን",         trans:"mamen",                    eng:"to believe"},
  {id:143,pos:"Verb",       cat:"Regular",             amh:"ማምጣት",        trans:"mamTat",                   eng:"to bring"},
  {id:144,pos:"Verb",       cat:"Regular",             amh:"ማሰብ",         trans:"maseb",                    eng:"to think"},
  {id:145,pos:"Verb",       cat:"Regular",             amh:"ማሳየት",        trans:"masayet",                  eng:"to show"},
  {id:146,pos:"Verb",       cat:"Regular",             amh:"ማስቀመጥ",       trans:"masqemeT",                 eng:"to put"},
  {id:147,pos:"Verb",       cat:"Regular",             amh:"ማስታወስ",       trans:"mastawes",                 eng:"to remember"},
  {id:148,pos:"Verb",       cat:"Regular",             amh:"ማሸነፍ",        trans:"mashenef",                 eng:"to win"},
  {id:149,pos:"Verb",       cat:"Regular",             amh:"ማቅረብ",        trans:"maqreb",                   eng:"to present / provide"},
  {id:150,pos:"Verb",       cat:"Regular",             amh:"ማንበብ",        trans:"manbeb",                   eng:"to read"},
  {id:151,pos:"Verb",       cat:"Regular",             amh:"ማወቅ",         trans:"maweq",                    eng:"to know"},
  {id:152,pos:"Verb",       cat:"Regular",             amh:"ማውጣት",        trans:"mawTat",                   eng:"to spend / take out"},
  {id:153,pos:"Verb",       cat:"Regular",             amh:"ማዘጋጀት",       trans:"mazegajet",                eng:"to prepare"},
  {id:154,pos:"Verb",       cat:"Regular",             amh:"ማየት",         trans:"mayet",                    eng:"to see"},
  {id:155,pos:"Verb",       cat:"Regular",             amh:"ማደግ",         trans:"madeg",                    eng:"to grow"},
  {id:156,pos:"Verb",       cat:"Regular",             amh:"ማድረግ",        trans:"madreg",                   eng:"to do"},
  {id:157,pos:"Verb",       cat:"Regular",             amh:"ማገልገል",       trans:"magelgel",                 eng:"to serve"},
  {id:158,pos:"Verb",       cat:"Regular",             amh:"ማጣት",         trans:"maTat",                    eng:"to lose"},
  {id:159,pos:"Verb",       cat:"Regular",             amh:"ማፍቀር",        trans:"mafqer",                   eng:"to love"},
  // ── Places & travel ──────────────────────────────────────────────
  {id:160,pos:"Noun",       cat:"Places",              amh:"ቤት",          trans:"bet",                      eng:"House/Home"},
  {id:161,pos:"Noun",       cat:"Places",              amh:"ት/ቤት",        trans:"timhirt bet",              eng:"School"},
  {id:162,pos:"Noun",       cat:"Places",              amh:"ሆስፒታል",       trans:"hospital",                 eng:"Hospital"},
  {id:163,pos:"Noun",       cat:"Places",              amh:"ገበያ",         trans:"gebeya",                   eng:"Market"},
  {id:164,pos:"Noun",       cat:"Places",              amh:"መስጊድ",        trans:"mesgid",                   eng:"Mosque"},
  {id:165,pos:"Noun",       cat:"Places",              amh:"ቤ/ክርስቲያን",    trans:"beta kristiyan",           eng:"Church"},
  {id:166,pos:"Noun",       cat:"Places",              amh:"ሆቴል",         trans:"hotel",                    eng:"Hotel"},
  {id:167,pos:"Noun",       cat:"Places",              amh:"ሬስቶራንት",      trans:"restorant",                eng:"Restaurant"},
  {id:168,pos:"Noun",       cat:"Places",              amh:"አየር ማረፊያ",    trans:"ayer marefiya",            eng:"Airport"},
  {id:169,pos:"Noun",       cat:"Places",              amh:"ጎዳና",         trans:"godana",                   eng:"Street/Road"},
  {id:170,pos:"Noun",       cat:"Places",              amh:"ሜዳ",          trans:"meda",                     eng:"Field/Park"},
  {id:171,pos:"Noun",       cat:"Places",              amh:"ከተማ",         trans:"ketema",                   eng:"City/Town"},
  // ── Food & drink ─────────────────────────────────────────────────
  {id:172,pos:"Noun",       cat:"Food & Drink",        amh:"ቡና",          trans:"buna",                     eng:"Coffee"},
  {id:173,pos:"Noun",       cat:"Food & Drink",        amh:"ውሃ",          trans:"wiha",                     eng:"Water"},
  {id:174,pos:"Noun",       cat:"Food & Drink",        amh:"ሻይ",          trans:"shay",                     eng:"Tea"},
  {id:175,pos:"Noun",       cat:"Food & Drink",        amh:"እንጀራ",        trans:"enjera",                   eng:"Injera (flatbread)"},
  {id:176,pos:"Noun",       cat:"Food & Drink",        amh:"ሥጋ",          trans:"siga",                     eng:"Meat"},
  {id:177,pos:"Noun",       cat:"Food & Drink",        amh:"ዳቦ",          trans:"dabo",                     eng:"Bread"},
  {id:178,pos:"Noun",       cat:"Food & Drink",        amh:"ወተት",         trans:"wetet",                    eng:"Milk"},
  {id:179,pos:"Noun",       cat:"Food & Drink",        amh:"ፍሬ",          trans:"fire",                     eng:"Fruit"},
  {id:180,pos:"Noun",       cat:"Food & Drink",        amh:"አትክልት",       trans:"atkilt",                   eng:"Vegetable"},
  {id:181,pos:"Noun",       cat:"Food & Drink",        amh:"ስኳር",         trans:"siquar",                   eng:"Sugar"},
  // ── Body ─────────────────────────────────────────────────────────
  {id:182,pos:"Noun",       cat:"Body",                amh:"ራስ",          trans:"ras",                      eng:"Head"},
  {id:183,pos:"Noun",       cat:"Body",                amh:"እጅ",          trans:"ij",                       eng:"Hand/Arm"},
  {id:184,pos:"Noun",       cat:"Body",                amh:"እግር",         trans:"igir",                     eng:"Foot/Leg"},
  {id:185,pos:"Noun",       cat:"Body",                amh:"አይን",         trans:"ayin",                     eng:"Eye"},
  {id:186,pos:"Noun",       cat:"Body",                amh:"አፍ",          trans:"af",                       eng:"Mouth"},
  {id:187,pos:"Noun",       cat:"Body",                amh:"ጆሮ",          trans:"joro",                     eng:"Ear"},
  {id:188,pos:"Noun",       cat:"Body",                amh:"አፍንጫ",        trans:"afnicha",                  eng:"Nose"},
  {id:189,pos:"Noun",       cat:"Body",                amh:"ሆድ",          trans:"hod",                      eng:"Stomach"},
  {id:190,pos:"Noun",       cat:"Body",                amh:"ጀርባ",         trans:"jerba",                    eng:"Back"},
  {id:191,pos:"Noun",       cat:"Body",                amh:"ልብ",          trans:"lib",                      eng:"Heart"},
];

// ── Fidel chart — 31 consonant rows × 7 vowel orders ─────────────
// Orders: [ä(uh), u(oo), i(ee), a(ah), ē(ay), ɨ(ih), o(oh)]
const fidelOrders = ["ä","u","i","a","ē","ɨ","o"];
const fidelOrderLabels = ["1st (ä/uh)","2nd (u/oo)","3rd (i/ee)","4th (a/ah)","5th (ē/ay)","6th (ɨ/ih)","7th (o/oh)"];

const fidelChart = [
  {name:"H",   rom:"h",    chars:["ሀ","ሁ","ሂ","ሃ","ሄ","ህ","ሆ"]},
  {name:"L",   rom:"l",    chars:["ለ","ሉ","ሊ","ላ","ሌ","ል","ሎ"]},
  {name:"Ħ",   rom:"ħ",    chars:["ሐ","ሑ","ሒ","ሓ","ሔ","ሕ","ሖ"]},
  {name:"M",   rom:"m",    chars:["መ","ሙ","ሚ","ማ","ሜ","ም","ሞ"]},
  {name:"Ś",   rom:"ś",    chars:["ሠ","ሡ","ሢ","ሣ","ሤ","ሥ","ሦ"]},
  {name:"R",   rom:"r",    chars:["ረ","ሩ","ሪ","ራ","ሬ","ር","ሮ"]},
  {name:"S",   rom:"s",    chars:["ሰ","ሱ","ሲ","ሳ","ሴ","ስ","ሶ"]},
  {name:"SH",  rom:"sh",   chars:["ሸ","ሹ","ሺ","ሻ","ሼ","ሽ","ሾ"]},
  {name:"Q",   rom:"q",    chars:["ቀ","ቁ","ቂ","ቃ","ቄ","ቅ","ቆ"]},
  {name:"B",   rom:"b",    chars:["በ","ቡ","ቢ","ባ","ቤ","ብ","ቦ"]},
  {name:"T",   rom:"t",    chars:["ተ","ቱ","ቲ","ታ","ቴ","ት","ቶ"]},
  {name:"CH",  rom:"ch",   chars:["ቸ","ቹ","ቺ","ቻ","ቼ","ች","ቾ"]},
  {name:"N",   rom:"n",    chars:["ነ","ኑ","ኒ","ና","ኔ","ን","ኖ"]},
  {name:"NY",  rom:"ny",   chars:["ኘ","ኙ","ኚ","ኛ","ኜ","ኝ","ኞ"]},
  {name:"A",   rom:"",     chars:["አ","ኡ","ኢ","ኣ","ኤ","እ","ኦ"]},
  {name:"K",   rom:"k",    chars:["ከ","ኩ","ኪ","ካ","ኬ","ክ","ኮ"]},
  {name:"KH",  rom:"kh",   chars:["ኸ","ኹ","ኺ","ኻ","ኼ","ኽ","ኾ"]},
  {name:"W",   rom:"w",    chars:["ወ","ዉ","ዊ","ዋ","ዌ","ው","ዎ"]},
  {name:"Z",   rom:"z",    chars:["ዘ","ዙ","ዚ","ዛ","ዜ","ዝ","ዞ"]},
  {name:"ZH",  rom:"zh",   chars:["ዠ","ዡ","ዢ","ዣ","ዤ","ዥ","ዦ"]},
  {name:"Y",   rom:"y",    chars:["የ","ዩ","ዪ","ያ","ዬ","ይ","ዮ"]},
  {name:"D",   rom:"d",    chars:["ደ","ዱ","ዲ","ዳ","ዴ","ድ","ዶ"]},
  {name:"J",   rom:"j",    chars:["ጀ","ጁ","ጂ","ጃ","ጄ","ጅ","ጆ"]},
  {name:"G",   rom:"g",    chars:["ገ","ጉ","ጊ","ጋ","ጌ","ግ","ጎ"]},
  {name:"T'",  rom:"t'",   chars:["ጠ","ጡ","ጢ","ጣ","ጤ","ጥ","ጦ"]},
  {name:"CH'", rom:"ch'",  chars:["ጨ","ጩ","ጪ","ጫ","ጬ","ጭ","ጮ"]},
  {name:"P'",  rom:"p'",   chars:["ጰ","ጱ","ጲ","ጳ","ጴ","ጵ","ጶ"]},
  {name:"TS'", rom:"ts'",  chars:["ጸ","ጹ","ጺ","ጻ","ጼ","ጽ","ጾ"]},
  {name:"Ṣ",   rom:"ṣ",    chars:["ፀ","ፁ","ፂ","ፃ","ፄ","ፅ","ፆ"]},
  {name:"F",   rom:"f",    chars:["ፈ","ፉ","ፊ","ፋ","ፌ","ፍ","ፎ"]},
  {name:"P",   rom:"p",    chars:["ፐ","ፑ","ፒ","ፓ","ፔ","ፕ","ፖ"]},
];

// ── Conjugation verb stems (from lesson document) ─────────────────
// Present progressive: iyye + stem + suffix + " new"
// vowelEnd: true means stem ends in a vowel (affects he/she/we suffixes)
const VERB_STEMS = [
  {amh:"መሄድ",   tr:"mehēd",   eng:"to go",          stem:"hēd",    vowelEnd:false},
  {amh:"መፈለግ",  tr:"mefelleg",eng:"to want",         stem:"felleg", vowelEnd:false},
  {amh:"ማፍቀር",  tr:"mafqer",  eng:"to love",         stem:"feqer",  vowelEnd:false},
  {amh:"ማየት",   tr:"mayet",   eng:"to see",          stem:"ayye",   vowelEnd:true},
  {amh:"ማወቅ",   tr:"mawek'",  eng:"to know",         stem:"awek'",  vowelEnd:false},
  {amh:"ማለት",   tr:"malet",   eng:"to say",          stem:"al",     vowelEnd:false},
  {amh:"መግባት",  tr:"megbat",  eng:"to enter",        stem:"geba",   vowelEnd:true},
  {amh:"መምጣት",  tr:"memt'at", eng:"to come",         stem:"met'a",  vowelEnd:true},
  {amh:"ማረፍ",   tr:"maref",   eng:"to rest",         stem:"aref",   vowelEnd:false},
  {amh:"መቻል",   tr:"mechal",  eng:"to be able",      stem:"chal",   vowelEnd:false},
  {amh:"መንገር",  tr:"menger",  eng:"to tell",         stem:"neger",  vowelEnd:false},
  {amh:"መስጠት",  tr:"mest'et", eng:"to give",         stem:"set'e",  vowelEnd:true},
  {amh:"መውሰድ",  tr:"mewsed",  eng:"to take",         stem:"wesed",  vowelEnd:false},
  {amh:"መማር",   tr:"memar",   eng:"to learn",        stem:"mar",    vowelEnd:false},
  {amh:"መናገር",  tr:"menager", eng:"to speak",        stem:"nager",  vowelEnd:false},
];

// ── 8 pronouns used in conjugation ───────────────────────────────
// suffix = used when stem ends in consonant (or always for I/You/You-pl/They)
// vSuffix = used when stem ends in vowel (only differs for He/She/We)
const PRONOUNS = [
  {label:"I",          amhScript:"እኔ",    amhRom:"ine",    suffix:"hu",     vSuffix:"hu"},
  {label:"You (m)",    amhScript:"አንተ",   amhRom:"ante",   suffix:"h",      vSuffix:"h"},
  {label:"You (f)",    amhScript:"አንቺ",   amhRom:"anchi",  suffix:"sh",     vSuffix:"sh"},
  {label:"He / It",   amhScript:"እሱ",    amhRom:"issu",   suffix:"e",      vSuffix:""},
  {label:"She",        amhScript:"እሷ",    amhRom:"issua",  suffix:"ech",    vSuffix:"ch"},
  {label:"We",         amhScript:"እኛ",    amhRom:"iña",    suffix:"en",     vSuffix:"n"},
  {label:"You (pl)",   amhScript:"እናንተ",  amhRom:"inante", suffix:"achihu", vSuffix:"achihu"},
  {label:"They",       amhScript:"እነሱ",   amhRom:"innessu",suffix:"achew",  vSuffix:"achew"},
];

// ── Sentence-generation verb pool ────────────────────────────────
const SENTENCE_VERBS = [
  {gerund:"wanting",    stem:"felleg", vowelEnd:false},
  {gerund:"taking",     stem:"wesed",  vowelEnd:false},
  {gerund:"seeing",     stem:"ayye",   vowelEnd:true},
  {gerund:"telling",    stem:"neger",  vowelEnd:false},
  {gerund:"learning",   stem:"mar",    vowelEnd:false},
];
